C:\WINDOWS\system32\cscript.exe d:\scripts\iislogcompress\iislogcompress.js 10 D:\websites\applications.mediavestww.com
C:\WINDOWS\system32\cscript.exe d:\scripts\iislogcompress\iislogcompress.js 10 D:\websites\www.agencyglowworm.com
C:\WINDOWS\system32\cscript.exe d:\scripts\iislogcompress\iislogcompress.js 10 D:\websites\bankofamerica.starcomworldwide.com
C:\WINDOWS\system32\cscript.exe d:\scripts\iislogcompress\iislogcompress.js 10 D:\websites\buzz.leoburnett.com
C:\WINDOWS\system32\cscript.exe d:\scripts\iislogcompress\iislogcompress.js 10 D:\websites\www.Denuogroup.com
C:\WINDOWS\system32\cscript.exe d:\scripts\iislogcompress\iislogcompress.js 10 D:\websites\content.missioncontrolglobal.com
C:\WINDOWS\system32\cscript.exe d:\scripts\iislogcompress\iislogcompress.js 10 D:\websites\www.halogenresponse.com
C:\WINDOWS\system32\cscript.exe d:\scripts\iislogcompress\iislogcompress.js 10 D:\websites\www.ITMarketing.PublicisGroupe.com
C:\WINDOWS\system32\cscript.exe d:\scripts\iislogcompress\iislogcompress.js 10 D:\websites\www.lbcity.biz
C:\WINDOWS\system32\cscript.exe d:\scripts\iislogcompress\iislogcompress.js 10 D:\websites\www.mediavestww.com
C:\WINDOWS\system32\cscript.exe d:\scripts\iislogcompress\iislogcompress.js 10 D:\websites\www.Mobility.PublicisGroupe.com
C:\WINDOWS\system32\cscript.exe d:\scripts\iislogcompress\iislogcompress.js 10 D:\websites\www.ninah.com
C:\WINDOWS\system32\cscript.exe d:\scripts\iislogcompress\iislogcompress.js 10 D:\websites\www.packagedgood.org
C:\WINDOWS\system32\cscript.exe d:\scripts\iislogcompress\iislogcompress.js 10 D:\websites\press.smvgroup.com
C:\WINDOWS\system32\cscript.exe d:\scripts\iislogcompress\iislogcompress.js 10 D:\websites\www.publicisboise.com
C:\WINDOWS\system32\cscript.exe d:\scripts\iislogcompress\iislogcompress.js 10 D:\websites\www.publiciscampaigns.com
C:\WINDOWS\system32\cscript.exe d:\scripts\iislogcompress\iislogcompress.js 10 D:\websites\www.publicisdialogstaging.com
C:\WINDOWS\system32\cscript.exe d:\scripts\iislogcompress\iislogcompress.js 10 D:\websites\www.publicisevents.com
C:\WINDOWS\system32\cscript.exe d:\scripts\iislogcompress\iislogcompress.js 10 D:\websites\www.publicisconsultants-pr.com
C:\WINDOWS\system32\cscript.exe d:\scripts\iislogcompress\iislogcompress.js 10 D:\websites\www.publicisinthewest.com
C:\WINDOWS\system32\cscript.exe d:\scripts\iislogcompress\iislogcompress.js 10 D:\websites\www.publicis-usa.com
C:\WINDOWS\system32\cscript.exe d:\scripts\iislogcompress\iislogcompress.js 10 D:\websites\www.publicisbos.com
C:\WINDOWS\system32\cscript.exe d:\scripts\iislogcompress\iislogcompress.js 10 D:\websites\www.tapestrypartners.com
C:\WINDOWS\system32\cscript.exe d:\scripts\iislogcompress\iislogcompress.js 10 D:\websites\www.sparksmg.com
C:\WINDOWS\system32\cscript.exe d:\scripts\iislogcompress\iislogcompress.js 10 D:\websites\www.smg-search.com
C:\WINDOWS\system32\cscript.exe d:\scripts\iislogcompress\iislogcompress.js 10 D:\websites\www.mslgroup.com
C:\WINDOWS\system32\cscript.exe d:\scripts\iislogcompress\iislogcompress.js 10 D:\websites\applications.smvgroup.com
C:\WINDOWS\system32\cscript.exe d:\scripts\iislogcompress\iislogcompress.js 10 D:\websites\ipad.mediavestww.com
C:\WINDOWS\system32\cscript.exe d:\scripts\iislogcompress\iislogcompress.js 10 D:\websites\judging.smvgroup.com
C:\WINDOWS\system32\cscript.exe d:\scripts\iislogcompress\iislogcompress.js 10 D:\websites\Redir-fluidtalentjobs.vivaki.com
C:\WINDOWS\system32\cscript.exe d:\scripts\iislogcompress\iislogcompress.js 10 D:\websites\REDIR-fluidtalent.vivaki.com
C:\WINDOWS\system32\cscript.exe d:\scripts\iislogcompress\iislogcompress.js 10 D:\websites\www.be-spoke.com
C:\WINDOWS\system32\cscript.exe d:\scripts\iislogcompress\iislogcompress.js 10 D:\websites\www.programexchange.com
